apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubeshare-frontend
  namespace: staging
spec:
  rules:
    - host: www.staging.kubeshare.com
    http:
      paths:
        path: /
        backend:
          serviceName: kubeshare-frontend
          servicePort: 80
